### ISSUE TITLE
Taking over

### ISSUE THREAD

**Issue by dalefrancis88** [francescobarbera/react-feature-switch#1]
Hey,

This appears to no longer be maintained, I've started to use it a bit more lately, do you mind if i took this over? I like the name and I think it has some potential

**Comment by francescobarbera** [comment]
Sorry for the late late late response. The library is currently used in some of our projects. We don't have any idea of an upgrade. Are you still interested in using it and working on it?

**Comment by dalefrancis88** [comment]
Yeah I am, I think there are a few things that could be changed and some great features that could be added
